version: '3'
services:
  mysql-localhost:
    build: "./docker/mysql/"
    container_name: "sami-thibault-mysql"
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=testdb_user
      - MYSQL_PASSWORD=123456789
  web:
    build: "./docker/web/"
    container_name: "sami-thibault-web"
    ports:
      - "80:80"
      - "443:443"
    restart: "no"
    volumes:
      - ./docker/web/public-html/:/var/www/html/